# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'food-order-application' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for food-order-application

pod 'Firebase/Auth'

end
